// Generated by CoffeeScript 1.6.2
(function() {
  var _ref;

  if ((_ref = window.svgize) == null) {
    window.svgize = function(src, canvasId, svgId, scale) {
      var context, img, svg;

      img = new Image();
      svg = document.getElementById(svgId);
      context = document.getElementById(canvasId).getContext('2d');
      img.onload = function() {
        var color, data, i, line, pixel, row, v, _i, _len, _results;

        svg.setAttribute('width', img.width * scale);
        svg.setAttribute('height', img.height * scale);
        context.drawImage(img, 0, 0);
        data = context.getImageData(0, 0, img.width, img.height).data;
        line = -1;
        row = 0;
        _results = [];
        for (i = _i = 0, _len = data.length; _i < _len; i = _i += 4) {
          v = data[i];
          row += 1;
          if ((i / 4) % img.width === 0) {
            line += 1;
            row = 0;
          }
          color = "rgba(" + data[i + 0] + "," + data[i + 1] + "," + data[i + 2] + "," + data[i + 3] + ")";
          pixel = document.createElementNS('http://www.w3.org/2000/svg', 'rect');
          pixel.setAttributeNS(null, 'x', row * scale);
          pixel.setAttributeNS(null, 'y', line * scale);
          pixel.setAttributeNS(null, 'width', scale);
          pixel.setAttributeNS(null, 'height', scale);
          pixel.setAttributeNS(null, 'fill', color);
          _results.push(svg.appendChild(pixel));
        }
        return _results;
      };
      img.src = src;
    };
  }

}).call(this);
